### ISSUE TITLE
mdessageId is null

### ISSUE THREAD

**Issue by brett-baudin-consulting** [brett-baudin-consulting/uMdali#21]
Track down the source of this error in the logs.
umdali-backend | error: undefined {"code":11000,"index":0,"keyPattern":{"messages.messageId":1},"keyValue":{"messages.messageId":null},"service":"user-service","timestamp":"2024-02-05 15:36:05"}

**Comment by brett-baudin-consulting** [comment]
conversationService.js:11 Uncaught (in promise) Error: HTTP error! status: 500 {"message":"E11000 duplicate key error collection: uMdali.conversations index: messages.messageId_1 dup key: { messages.messageId: null }"}
    at conversationService.js:11:13
    at p (regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (regeneratorRuntime.js:133:17)
    at Generator.next (regeneratorRuntime.js:74:21)
    at nt (asyncToGenerator.js:3:20)
    at o (asyncToGenerator.js:22:9)
